# Copyright (c) 2025 Tylt LLC. All rights reserved.
# Derivative works may be released by researchers,
# but original files may not be redistributed or used beyond research purposes.

"""Core framework classes and DSL functions."""

from cudag.core.coords import (
    RU_MAX,
    clamp_coord,
    coord_distance,
    coord_within_tolerance,
    get_normalized_bounds,
    normalize_coord,
    pixel_from_normalized,
)
from cudag.core.dataset import DatasetBuilder, DatasetConfig
from cudag.core.models import (
    # Classes
    Attachment,
    BelongsToRel,
    BoolField,
    ChoiceField,
    Claim,
    ComputedField,
    DateField,
    Field,
    FloatField,
    HasManyRel,
    HasOneRel,
    IntField,
    ListField,
    Model,
    ModelGenerator,
    MoneyField,
    Patient,
    Procedure,
    Provider,
    Relationship,
    StringField,
    TimeField,
    # DSL functions
    attribute,
    belongs_to,
    boolean,
    choice,
    computed,
    date_field,
    decimal,
    has_many,
    has_one,
    integer,
    list_of,
    money,
    string,
    time_field,
    years_since,
    # Semantic field types
    City,
    ClaimNumber,
    ClaimStatus,
    DOB,
    Email,
    Fee,
    FirstName,
    FullName,
    LastName,
    LicenseNumber,
    MemberID,
    NPI,
    Phone,
    ProcedureCode,
    SSN,
    Specialty,
    State,
    Street,
    ZipCode,
)
from cudag.core.renderer import BaseRenderer
from cudag.core.screen import (
    # Classes
    Bounds,
    ButtonRegion,
    ClickRegion,
    DropdownRegion,
    GridRegion,
    Region,
    Screen,
    ScreenBase,
    ScreenMeta,
    ScrollRegion,
    # DSL functions
    button,
    dropdown,
    grid,
    region,
    scrollable,
)
from cudag.core.state import BaseState, ScrollState
from cudag.core.task import BaseTask, EvalCase, TaskContext, TaskSample

__all__ = [
    # Coordinates
    "RU_MAX",
    "normalize_coord",
    "pixel_from_normalized",
    "get_normalized_bounds",
    "clamp_coord",
    "coord_distance",
    "coord_within_tolerance",
    # Screen DSL - classes
    "Screen",
    "ScreenBase",
    "ScreenMeta",
    "Region",
    "Bounds",
    "ClickRegion",
    "ButtonRegion",
    "GridRegion",
    "ScrollRegion",
    "DropdownRegion",
    # Screen DSL - functions
    "region",
    "button",
    "grid",
    "scrollable",
    "dropdown",
    # State
    "BaseState",
    "ScrollState",
    # Renderer
    "BaseRenderer",
    # Task
    "BaseTask",
    "TaskSample",
    "TaskContext",
    "EvalCase",
    # Dataset
    "DatasetBuilder",
    "DatasetConfig",
    # Model DSL - classes
    "Model",
    "ModelGenerator",
    "Field",
    "StringField",
    "IntField",
    "FloatField",
    "BoolField",
    "DateField",
    "TimeField",
    "ChoiceField",
    "ListField",
    "MoneyField",
    "ComputedField",
    # Model DSL - functions
    "attribute",
    "string",
    "integer",
    "decimal",
    "money",
    "date_field",
    "time_field",
    "boolean",
    "choice",
    "list_of",
    "computed",
    "years_since",
    # Relationship DSL - classes
    "Relationship",
    "HasManyRel",
    "BelongsToRel",
    "HasOneRel",
    # Relationship DSL - functions
    "has_many",
    "belongs_to",
    "has_one",
    # Common healthcare models
    "Patient",
    "Provider",
    "Procedure",
    "Claim",
    "Attachment",
    # Semantic field types
    "FirstName",
    "LastName",
    "FullName",
    "DOB",
    "NPI",
    "SSN",
    "Phone",
    "Email",
    "Street",
    "City",
    "State",
    "ZipCode",
    "MemberID",
    "ClaimNumber",
    "ProcedureCode",
    "LicenseNumber",
    "Specialty",
    "ClaimStatus",
    "Fee",
]
